# Generated by Django 3.2.4 on 2021-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Founder', 'Founder'), ('MasterChef', 'Master Chef'), ('MasterBaker', 'Master Baker'), ('JuniorBaker', 'Junior Baker')], default='JuniorBaker', max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
