# Generated by Django 3.2.4 on 2021-06-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
