# Generated by Django 3.2.4 on 2021-06-04 10:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bakers', '0003_alter_baker_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baker',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='photos/%Y/%m/%d/'),
        ),
    ]
