# Generated by Django 3.2.4 on 2021-06-06 19:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='photos/%Y/%m/%d/'),
        ),
    ]
