# Generated by Django 3.2.4 on 2021-06-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-added_on']},
        ),
    ]
